import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import dynamic from "next/dynamic";
import Head from "next/head";

const FAQ = dynamic(() => import("@/components/FAQ").then((mod) => mod.FAQ), { ssr: false });
const Swap = dynamic(() => import("@/components").then((mod) => mod.Swap), { ssr: false });
const Wallet = dynamic(() => import("@/components").then((mod) => mod.Wallet), { ssr: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Grid container spacing={6}>
          <Grid item xs md={3.5}>
            <Wallet />
          </Grid>
          <Grid item xs={12} sm={8} md={5}>
            <Swap />
          </Grid>
          <Grid item xs sm={3.5}>
            <FAQ />
          </Grid>
        </Grid>
      </Box>
    </>
  );
}
