import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import dynamic from "next/dynamic";
import Head from "next/head";


const { DATABASE_URL } = process.env

const FAQ = dynamic(() => import("@/components").then((mod) => mod.FAQ), { ssr: false });
const Swap = dynamic(() => import("@/components").then((mod) => mod.Swap), { ssr: false });

// Define props

export default function Home() {
  return (
    <>
      <Head>
        <title>Exchange App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Grid container spacing={6}>
          <Grid item xs md={3.5} sx={{ display: { xs: "none", md: "block" } }}></Grid>
          <Grid item xs={12} sm={8} md={5}>
            <Swap />
          </Grid>
          <Grid item xs sm={3.5}>
            <FAQ />
          </Grid>
        </Grid>
      </Box>
    </>
  );
}
